// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: BaseApi.proto

package basepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseBlock struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	ParentHash      string                  `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	FeeRecipient    string                  `protobuf:"bytes,2,opt,name=fee_recipient,json=feeRecipient,proto3" json:"fee_recipient,omitempty"`
	StateRoot       []byte                  `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	ReceiptsRoot    []byte                  `protobuf:"bytes,4,opt,name=receipts_root,json=receiptsRoot,proto3" json:"receipts_root,omitempty"`
	LogsBloom       []byte                  `protobuf:"bytes,5,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	PrevRandao      []byte                  `protobuf:"bytes,6,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty"`
	BlockNumber     uint64                  `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	GasLimit        uint64                  `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed         uint64                  `protobuf:"varint,9,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp       uint64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData       []byte                  `protobuf:"bytes,11,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	BaseFeePerGas   []uint64                `protobuf:"varint,12,rep,packed,name=base_fee_per_gas,json=baseFeePerGas,proto3" json:"base_fee_per_gas,omitempty"`
	BlockHash       string                  `protobuf:"bytes,13,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Transactions    [][]byte                `protobuf:"bytes,14,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Withdrawals     []*Withdrawal           `protobuf:"bytes,15,rep,name=withdrawals,proto3" json:"withdrawals,omitempty"`
	BlobGasUsed     *wrapperspb.UInt64Value `protobuf:"bytes,16,opt,name=blob_gas_used,json=blobGasUsed,proto3" json:"blob_gas_used,omitempty"`
	ExcessBlobGas   *wrapperspb.UInt64Value `protobuf:"bytes,17,opt,name=excess_blob_gas,json=excessBlobGas,proto3" json:"excess_blob_gas,omitempty"`
	WithdrawalsRoot *wrapperspb.BytesValue  `protobuf:"bytes,18,opt,name=withdrawals_root,json=withdrawalsRoot,proto3" json:"withdrawals_root,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BaseBlock) Reset() {
	*x = BaseBlock{}
	mi := &file_BaseApi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseBlock) ProtoMessage() {}

func (x *BaseBlock) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseBlock.ProtoReflect.Descriptor instead.
func (*BaseBlock) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{0}
}

func (x *BaseBlock) GetParentHash() string {
	if x != nil {
		return x.ParentHash
	}
	return ""
}

func (x *BaseBlock) GetFeeRecipient() string {
	if x != nil {
		return x.FeeRecipient
	}
	return ""
}

func (x *BaseBlock) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BaseBlock) GetReceiptsRoot() []byte {
	if x != nil {
		return x.ReceiptsRoot
	}
	return nil
}

func (x *BaseBlock) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *BaseBlock) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *BaseBlock) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BaseBlock) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *BaseBlock) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *BaseBlock) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BaseBlock) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *BaseBlock) GetBaseFeePerGas() []uint64 {
	if x != nil {
		return x.BaseFeePerGas
	}
	return nil
}

func (x *BaseBlock) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *BaseBlock) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *BaseBlock) GetWithdrawals() []*Withdrawal {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

func (x *BaseBlock) GetBlobGasUsed() *wrapperspb.UInt64Value {
	if x != nil {
		return x.BlobGasUsed
	}
	return nil
}

func (x *BaseBlock) GetExcessBlobGas() *wrapperspb.UInt64Value {
	if x != nil {
		return x.ExcessBlobGas
	}
	return nil
}

func (x *BaseBlock) GetWithdrawalsRoot() *wrapperspb.BytesValue {
	if x != nil {
		return x.WithdrawalsRoot
	}
	return nil
}

type Withdrawal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Validator     uint64                 `protobuf:"varint,2,opt,name=validator,proto3" json:"validator,omitempty"`
	Address       []byte                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Amount        uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Withdrawal) Reset() {
	*x = Withdrawal{}
	mi := &file_BaseApi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Withdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Withdrawal) ProtoMessage() {}

func (x *Withdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Withdrawal.ProtoReflect.Descriptor instead.
func (*Withdrawal) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{1}
}

func (x *Withdrawal) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Withdrawal) GetValidator() uint64 {
	if x != nil {
		return x.Validator
	}
	return 0
}

func (x *Withdrawal) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Withdrawal) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetRawFlashBlocksStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRawFlashBlocksStreamRequest) Reset() {
	*x = GetRawFlashBlocksStreamRequest{}
	mi := &file_BaseApi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRawFlashBlocksStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRawFlashBlocksStreamRequest) ProtoMessage() {}

func (x *GetRawFlashBlocksStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRawFlashBlocksStreamRequest.ProtoReflect.Descriptor instead.
func (*GetRawFlashBlocksStreamRequest) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{2}
}

type GetBlockStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockStreamRequest) Reset() {
	*x = GetBlockStreamRequest{}
	mi := &file_BaseApi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockStreamRequest) ProtoMessage() {}

func (x *GetBlockStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockStreamRequest.ProtoReflect.Descriptor instead.
func (*GetBlockStreamRequest) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{3}
}

type SendTransactionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RawTransaction string                 `protobuf:"bytes,1,opt,name=rawTransaction,proto3" json:"rawTransaction,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendTransactionRequest) Reset() {
	*x = SendTransactionRequest{}
	mi := &file_BaseApi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionRequest) ProtoMessage() {}

func (x *SendTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionRequest.ProtoReflect.Descriptor instead.
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{4}
}

func (x *SendTransactionRequest) GetRawTransaction() string {
	if x != nil {
		return x.RawTransaction
	}
	return ""
}

type SendTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTransactionResponse) Reset() {
	*x = SendTransactionResponse{}
	mi := &file_BaseApi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionResponse) ProtoMessage() {}

func (x *SendTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionResponse.ProtoReflect.Descriptor instead.
func (*SendTransactionResponse) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{5}
}

func (x *SendTransactionResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type FlashBlockStrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlashBlockStrRequest) Reset() {
	*x = FlashBlockStrRequest{}
	mi := &file_BaseApi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashBlockStrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashBlockStrRequest) ProtoMessage() {}

func (x *FlashBlockStrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashBlockStrRequest.ProtoReflect.Descriptor instead.
func (*FlashBlockStrRequest) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{6}
}

type RawFlashBlockStrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawFlashBlockStrResponse) Reset() {
	*x = RawFlashBlockStrResponse{}
	mi := &file_BaseApi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawFlashBlockStrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawFlashBlockStrResponse) ProtoMessage() {}

func (x *RawFlashBlockStrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawFlashBlockStrResponse.ProtoReflect.Descriptor instead.
func (*RawFlashBlockStrResponse) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{7}
}

func (x *RawFlashBlockStrResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_BaseApi_proto protoreflect.FileDescriptor

const file_BaseApi_proto_rawDesc = "" +
	"\n" +
	"\rBaseApi.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xd8\x05\n" +
	"\tBaseBlock\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\tR\n" +
	"parentHash\x12#\n" +
	"\rfee_recipient\x18\x02 \x01(\tR\ffeeRecipient\x12\x1d\n" +
	"\n" +
	"state_root\x18\x03 \x01(\fR\tstateRoot\x12#\n" +
	"\rreceipts_root\x18\x04 \x01(\fR\freceiptsRoot\x12\x1d\n" +
	"\n" +
	"logs_bloom\x18\x05 \x01(\fR\tlogsBloom\x12\x1f\n" +
	"\vprev_randao\x18\x06 \x01(\fR\n" +
	"prevRandao\x12!\n" +
	"\fblock_number\x18\a \x01(\x04R\vblockNumber\x12\x1b\n" +
	"\tgas_limit\x18\b \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\t \x01(\x04R\agasUsed\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"extra_data\x18\v \x01(\fR\textraData\x12'\n" +
	"\x10base_fee_per_gas\x18\f \x03(\x04R\rbaseFeePerGas\x12\x1d\n" +
	"\n" +
	"block_hash\x18\r \x01(\tR\tblockHash\x12\"\n" +
	"\ftransactions\x18\x0e \x03(\fR\ftransactions\x12-\n" +
	"\vwithdrawals\x18\x0f \x03(\v2\v.WithdrawalR\vwithdrawals\x12@\n" +
	"\rblob_gas_used\x18\x10 \x01(\v2\x1c.google.protobuf.UInt64ValueR\vblobGasUsed\x12D\n" +
	"\x0fexcess_blob_gas\x18\x11 \x01(\v2\x1c.google.protobuf.UInt64ValueR\rexcessBlobGas\x12F\n" +
	"\x10withdrawals_root\x18\x12 \x01(\v2\x1b.google.protobuf.BytesValueR\x0fwithdrawalsRoot\"r\n" +
	"\n" +
	"Withdrawal\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x1c\n" +
	"\tvalidator\x18\x02 \x01(\x04R\tvalidator\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\fR\aaddress\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\" \n" +
	"\x1eGetRawFlashBlocksStreamRequest\"\x17\n" +
	"\x15GetBlockStreamRequest\"@\n" +
	"\x16SendTransactionRequest\x12&\n" +
	"\x0erawTransaction\x18\x01 \x01(\tR\x0erawTransaction\"1\n" +
	"\x17SendTransactionResponse\x12\x16\n" +
	"\x06txHash\x18\x01 \x01(\tR\x06txHash\"\x16\n" +
	"\x14FlashBlockStrRequest\"4\n" +
	"\x18RawFlashBlockStrResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage2\xdf\x01\n" +
	"\aBaseApi\x12D\n" +
	"\x0fSendTransaction\x12\x17.SendTransactionRequest\x1a\x18.SendTransactionResponse\x126\n" +
	"\x0eGetBlockStream\x12\x16.GetBlockStreamRequest\x1a\n" +
	".BaseBlock0\x01\x12V\n" +
	"\x16GetRawFlashBlockStream\x12\x1f.GetRawFlashBlocksStreamRequest\x1a\x19.RawFlashBlockStrResponse0\x01B\n" +
	"Z\b./basepbb\x06proto3"

var (
	file_BaseApi_proto_rawDescOnce sync.Once
	file_BaseApi_proto_rawDescData []byte
)

func file_BaseApi_proto_rawDescGZIP() []byte {
	file_BaseApi_proto_rawDescOnce.Do(func() {
		file_BaseApi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_BaseApi_proto_rawDesc), len(file_BaseApi_proto_rawDesc)))
	})
	return file_BaseApi_proto_rawDescData
}

var file_BaseApi_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_BaseApi_proto_goTypes = []any{
	(*BaseBlock)(nil),                      // 0: BaseBlock
	(*Withdrawal)(nil),                     // 1: Withdrawal
	(*GetRawFlashBlocksStreamRequest)(nil), // 2: GetRawFlashBlocksStreamRequest
	(*GetBlockStreamRequest)(nil),          // 3: GetBlockStreamRequest
	(*SendTransactionRequest)(nil),         // 4: SendTransactionRequest
	(*SendTransactionResponse)(nil),        // 5: SendTransactionResponse
	(*FlashBlockStrRequest)(nil),           // 6: FlashBlockStrRequest
	(*RawFlashBlockStrResponse)(nil),       // 7: RawFlashBlockStrResponse
	(*wrapperspb.UInt64Value)(nil),         // 8: google.protobuf.UInt64Value
	(*wrapperspb.BytesValue)(nil),          // 9: google.protobuf.BytesValue
}
var file_BaseApi_proto_depIdxs = []int32{
	1, // 0: BaseBlock.withdrawals:type_name -> Withdrawal
	8, // 1: BaseBlock.blob_gas_used:type_name -> google.protobuf.UInt64Value
	8, // 2: BaseBlock.excess_blob_gas:type_name -> google.protobuf.UInt64Value
	9, // 3: BaseBlock.withdrawals_root:type_name -> google.protobuf.BytesValue
	4, // 4: BaseApi.SendTransaction:input_type -> SendTransactionRequest
	3, // 5: BaseApi.GetBlockStream:input_type -> GetBlockStreamRequest
	2, // 6: BaseApi.GetRawFlashBlockStream:input_type -> GetRawFlashBlocksStreamRequest
	5, // 7: BaseApi.SendTransaction:output_type -> SendTransactionResponse
	0, // 8: BaseApi.GetBlockStream:output_type -> BaseBlock
	7, // 9: BaseApi.GetRawFlashBlockStream:output_type -> RawFlashBlockStrResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_BaseApi_proto_init() }
func file_BaseApi_proto_init() {
	if File_BaseApi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_BaseApi_proto_rawDesc), len(file_BaseApi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_BaseApi_proto_goTypes,
		DependencyIndexes: file_BaseApi_proto_depIdxs,
		MessageInfos:      file_BaseApi_proto_msgTypes,
	}.Build()
	File_BaseApi_proto = out.File
	file_BaseApi_proto_goTypes = nil
	file_BaseApi_proto_depIdxs = nil
}
