// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: BaseApi.proto

package basepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseBlock struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	ParentHash      string                  `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	FeeRecipient    string                  `protobuf:"bytes,2,opt,name=fee_recipient,json=feeRecipient,proto3" json:"fee_recipient,omitempty"`
	StateRoot       []byte                  `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	ReceiptsRoot    []byte                  `protobuf:"bytes,4,opt,name=receipts_root,json=receiptsRoot,proto3" json:"receipts_root,omitempty"`
	LogsBloom       []byte                  `protobuf:"bytes,5,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	PrevRandao      []byte                  `protobuf:"bytes,6,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty"`
	BlockNumber     uint64                  `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	GasLimit        uint64                  `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed         uint64                  `protobuf:"varint,9,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp       uint64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData       []byte                  `protobuf:"bytes,11,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	BaseFeePerGas   []uint64                `protobuf:"varint,12,rep,packed,name=base_fee_per_gas,json=baseFeePerGas,proto3" json:"base_fee_per_gas,omitempty"`
	BlockHash       string                  `protobuf:"bytes,13,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Transactions    [][]byte                `protobuf:"bytes,14,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Withdrawals     []*Withdrawal           `protobuf:"bytes,15,rep,name=withdrawals,proto3" json:"withdrawals,omitempty"`
	BlobGasUsed     *wrapperspb.UInt64Value `protobuf:"bytes,16,opt,name=blob_gas_used,json=blobGasUsed,proto3" json:"blob_gas_used,omitempty"`
	ExcessBlobGas   *wrapperspb.UInt64Value `protobuf:"bytes,17,opt,name=excess_blob_gas,json=excessBlobGas,proto3" json:"excess_blob_gas,omitempty"`
	WithdrawalsRoot *wrapperspb.BytesValue  `protobuf:"bytes,18,opt,name=withdrawals_root,json=withdrawalsRoot,proto3" json:"withdrawals_root,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BaseBlock) Reset() {
	*x = BaseBlock{}
	mi := &file_BaseApi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseBlock) ProtoMessage() {}

func (x *BaseBlock) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseBlock.ProtoReflect.Descriptor instead.
func (*BaseBlock) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{0}
}

func (x *BaseBlock) GetParentHash() string {
	if x != nil {
		return x.ParentHash
	}
	return ""
}

func (x *BaseBlock) GetFeeRecipient() string {
	if x != nil {
		return x.FeeRecipient
	}
	return ""
}

func (x *BaseBlock) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BaseBlock) GetReceiptsRoot() []byte {
	if x != nil {
		return x.ReceiptsRoot
	}
	return nil
}

func (x *BaseBlock) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *BaseBlock) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *BaseBlock) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BaseBlock) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *BaseBlock) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *BaseBlock) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BaseBlock) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *BaseBlock) GetBaseFeePerGas() []uint64 {
	if x != nil {
		return x.BaseFeePerGas
	}
	return nil
}

func (x *BaseBlock) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *BaseBlock) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *BaseBlock) GetWithdrawals() []*Withdrawal {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

func (x *BaseBlock) GetBlobGasUsed() *wrapperspb.UInt64Value {
	if x != nil {
		return x.BlobGasUsed
	}
	return nil
}

func (x *BaseBlock) GetExcessBlobGas() *wrapperspb.UInt64Value {
	if x != nil {
		return x.ExcessBlobGas
	}
	return nil
}

func (x *BaseBlock) GetWithdrawalsRoot() *wrapperspb.BytesValue {
	if x != nil {
		return x.WithdrawalsRoot
	}
	return nil
}

type Withdrawal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Validator     uint64                 `protobuf:"varint,2,opt,name=validator,proto3" json:"validator,omitempty"`
	Address       []byte                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Amount        uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Withdrawal) Reset() {
	*x = Withdrawal{}
	mi := &file_BaseApi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Withdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Withdrawal) ProtoMessage() {}

func (x *Withdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Withdrawal.ProtoReflect.Descriptor instead.
func (*Withdrawal) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{1}
}

func (x *Withdrawal) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Withdrawal) GetValidator() uint64 {
	if x != nil {
		return x.Validator
	}
	return 0
}

func (x *Withdrawal) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Withdrawal) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetRawFlashBlocksStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRawFlashBlocksStreamRequest) Reset() {
	*x = GetRawFlashBlocksStreamRequest{}
	mi := &file_BaseApi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRawFlashBlocksStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRawFlashBlocksStreamRequest) ProtoMessage() {}

func (x *GetRawFlashBlocksStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRawFlashBlocksStreamRequest.ProtoReflect.Descriptor instead.
func (*GetRawFlashBlocksStreamRequest) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{2}
}

type GetBlockStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockStreamRequest) Reset() {
	*x = GetBlockStreamRequest{}
	mi := &file_BaseApi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockStreamRequest) ProtoMessage() {}

func (x *GetBlockStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockStreamRequest.ProtoReflect.Descriptor instead.
func (*GetBlockStreamRequest) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{3}
}

type SendTransactionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RawTransaction string                 `protobuf:"bytes,1,opt,name=rawTransaction,proto3" json:"rawTransaction,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendTransactionRequest) Reset() {
	*x = SendTransactionRequest{}
	mi := &file_BaseApi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionRequest) ProtoMessage() {}

func (x *SendTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionRequest.ProtoReflect.Descriptor instead.
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{4}
}

func (x *SendTransactionRequest) GetRawTransaction() string {
	if x != nil {
		return x.RawTransaction
	}
	return ""
}

type SendTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTransactionResponse) Reset() {
	*x = SendTransactionResponse{}
	mi := &file_BaseApi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionResponse) ProtoMessage() {}

func (x *SendTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionResponse.ProtoReflect.Descriptor instead.
func (*SendTransactionResponse) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{5}
}

func (x *SendTransactionResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type FlashBlockStrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlashBlockStrRequest) Reset() {
	*x = FlashBlockStrRequest{}
	mi := &file_BaseApi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashBlockStrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashBlockStrRequest) ProtoMessage() {}

func (x *FlashBlockStrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashBlockStrRequest.ProtoReflect.Descriptor instead.
func (*FlashBlockStrRequest) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{6}
}

type RawFlashBlockStrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawFlashBlockStrResponse) Reset() {
	*x = RawFlashBlockStrResponse{}
	mi := &file_BaseApi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawFlashBlockStrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawFlashBlockStrResponse) ProtoMessage() {}

func (x *RawFlashBlockStrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawFlashBlockStrResponse.ProtoReflect.Descriptor instead.
func (*RawFlashBlockStrResponse) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{7}
}

func (x *RawFlashBlockStrResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type GetNewFlashblockTransactionsStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewFlashblockTransactionsStreamRequest) Reset() {
	*x = GetNewFlashblockTransactionsStreamRequest{}
	mi := &file_BaseApi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewFlashblockTransactionsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewFlashblockTransactionsStreamRequest) ProtoMessage() {}

func (x *GetNewFlashblockTransactionsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewFlashblockTransactionsStreamRequest.ProtoReflect.Descriptor instead.
func (*GetNewFlashblockTransactionsStreamRequest) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{8}
}

type NewFlashblockTransactionAccessListEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	StorageKeys   []string               `protobuf:"bytes,2,rep,name=storage_keys,json=storageKeys,proto3" json:"storage_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewFlashblockTransactionAccessListEntry) Reset() {
	*x = NewFlashblockTransactionAccessListEntry{}
	mi := &file_BaseApi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewFlashblockTransactionAccessListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewFlashblockTransactionAccessListEntry) ProtoMessage() {}

func (x *NewFlashblockTransactionAccessListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewFlashblockTransactionAccessListEntry.ProtoReflect.Descriptor instead.
func (*NewFlashblockTransactionAccessListEntry) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{9}
}

func (x *NewFlashblockTransactionAccessListEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NewFlashblockTransactionAccessListEntry) GetStorageKeys() []string {
	if x != nil {
		return x.StorageKeys
	}
	return nil
}

type NewFlashblockTransactionLog struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Address          string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Topics           []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data             string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	BlockHash        string                 `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockNumber      string                 `protobuf:"bytes,5,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockTimestamp   string                 `protobuf:"bytes,6,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	TransactionHash  string                 `protobuf:"bytes,7,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	TransactionIndex string                 `protobuf:"bytes,8,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	LogIndex         string                 `protobuf:"bytes,9,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	Removed          bool                   `protobuf:"varint,10,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NewFlashblockTransactionLog) Reset() {
	*x = NewFlashblockTransactionLog{}
	mi := &file_BaseApi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewFlashblockTransactionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewFlashblockTransactionLog) ProtoMessage() {}

func (x *NewFlashblockTransactionLog) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewFlashblockTransactionLog.ProtoReflect.Descriptor instead.
func (*NewFlashblockTransactionLog) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{10}
}

func (x *NewFlashblockTransactionLog) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NewFlashblockTransactionLog) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *NewFlashblockTransactionLog) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *NewFlashblockTransactionLog) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *NewFlashblockTransactionLog) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *NewFlashblockTransactionLog) GetBlockTimestamp() string {
	if x != nil {
		return x.BlockTimestamp
	}
	return ""
}

func (x *NewFlashblockTransactionLog) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *NewFlashblockTransactionLog) GetTransactionIndex() string {
	if x != nil {
		return x.TransactionIndex
	}
	return ""
}

func (x *NewFlashblockTransactionLog) GetLogIndex() string {
	if x != nil {
		return x.LogIndex
	}
	return ""
}

func (x *NewFlashblockTransactionLog) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type NewFlashblockTransaction struct {
	state                protoimpl.MessageState                     `protogen:"open.v1"`
	Type                 string                                     `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ChainId              string                                     `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Nonce                string                                     `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Gas                  string                                     `protobuf:"bytes,4,opt,name=gas,proto3" json:"gas,omitempty"`
	MaxFeePerGas         string                                     `protobuf:"bytes,5,opt,name=max_fee_per_gas,json=maxFeePerGas,proto3" json:"max_fee_per_gas,omitempty"`
	MaxPriorityFeePerGas string                                     `protobuf:"bytes,6,opt,name=max_priority_fee_per_gas,json=maxPriorityFeePerGas,proto3" json:"max_priority_fee_per_gas,omitempty"`
	To                   *wrapperspb.StringValue                    `protobuf:"bytes,7,opt,name=to,proto3" json:"to,omitempty"`
	Value                string                                     `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`
	AccessList           []*NewFlashblockTransactionAccessListEntry `protobuf:"bytes,9,rep,name=access_list,json=accessList,proto3" json:"access_list,omitempty"`
	Input                string                                     `protobuf:"bytes,10,opt,name=input,proto3" json:"input,omitempty"`
	R                    string                                     `protobuf:"bytes,11,opt,name=r,proto3" json:"r,omitempty"`
	S                    string                                     `protobuf:"bytes,12,opt,name=s,proto3" json:"s,omitempty"`
	YParity              string                                     `protobuf:"bytes,13,opt,name=y_parity,json=yParity,proto3" json:"y_parity,omitempty"`
	V                    string                                     `protobuf:"bytes,14,opt,name=v,proto3" json:"v,omitempty"`
	Hash                 string                                     `protobuf:"bytes,15,opt,name=hash,proto3" json:"hash,omitempty"`
	BlockHash            *wrapperspb.StringValue                    `protobuf:"bytes,16,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockNumber          string                                     `protobuf:"bytes,17,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TransactionIndex     string                                     `protobuf:"bytes,18,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	BlockTimestamp       string                                     `protobuf:"bytes,19,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	From                 string                                     `protobuf:"bytes,20,opt,name=from,proto3" json:"from,omitempty"`
	GasPrice             string                                     `protobuf:"bytes,21,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	Logs                 []*NewFlashblockTransactionLog             `protobuf:"bytes,22,rep,name=logs,proto3" json:"logs,omitempty"`
	GasUsed              string                                     `protobuf:"bytes,23,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Status               string                                     `protobuf:"bytes,24,opt,name=status,proto3" json:"status,omitempty"`
	CumulativeGasUsed    string                                     `protobuf:"bytes,25,opt,name=cumulative_gas_used,json=cumulativeGasUsed,proto3" json:"cumulative_gas_used,omitempty"`
	ContractAddress      *wrapperspb.StringValue                    `protobuf:"bytes,26,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	LogsBloom            string                                     `protobuf:"bytes,27,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NewFlashblockTransaction) Reset() {
	*x = NewFlashblockTransaction{}
	mi := &file_BaseApi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewFlashblockTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewFlashblockTransaction) ProtoMessage() {}

func (x *NewFlashblockTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_BaseApi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewFlashblockTransaction.ProtoReflect.Descriptor instead.
func (*NewFlashblockTransaction) Descriptor() ([]byte, []int) {
	return file_BaseApi_proto_rawDescGZIP(), []int{11}
}

func (x *NewFlashblockTransaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NewFlashblockTransaction) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *NewFlashblockTransaction) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *NewFlashblockTransaction) GetGas() string {
	if x != nil {
		return x.Gas
	}
	return ""
}

func (x *NewFlashblockTransaction) GetMaxFeePerGas() string {
	if x != nil {
		return x.MaxFeePerGas
	}
	return ""
}

func (x *NewFlashblockTransaction) GetMaxPriorityFeePerGas() string {
	if x != nil {
		return x.MaxPriorityFeePerGas
	}
	return ""
}

func (x *NewFlashblockTransaction) GetTo() *wrapperspb.StringValue {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *NewFlashblockTransaction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *NewFlashblockTransaction) GetAccessList() []*NewFlashblockTransactionAccessListEntry {
	if x != nil {
		return x.AccessList
	}
	return nil
}

func (x *NewFlashblockTransaction) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *NewFlashblockTransaction) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

func (x *NewFlashblockTransaction) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *NewFlashblockTransaction) GetYParity() string {
	if x != nil {
		return x.YParity
	}
	return ""
}

func (x *NewFlashblockTransaction) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *NewFlashblockTransaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *NewFlashblockTransaction) GetBlockHash() *wrapperspb.StringValue {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *NewFlashblockTransaction) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *NewFlashblockTransaction) GetTransactionIndex() string {
	if x != nil {
		return x.TransactionIndex
	}
	return ""
}

func (x *NewFlashblockTransaction) GetBlockTimestamp() string {
	if x != nil {
		return x.BlockTimestamp
	}
	return ""
}

func (x *NewFlashblockTransaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *NewFlashblockTransaction) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *NewFlashblockTransaction) GetLogs() []*NewFlashblockTransactionLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *NewFlashblockTransaction) GetGasUsed() string {
	if x != nil {
		return x.GasUsed
	}
	return ""
}

func (x *NewFlashblockTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NewFlashblockTransaction) GetCumulativeGasUsed() string {
	if x != nil {
		return x.CumulativeGasUsed
	}
	return ""
}

func (x *NewFlashblockTransaction) GetContractAddress() *wrapperspb.StringValue {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *NewFlashblockTransaction) GetLogsBloom() string {
	if x != nil {
		return x.LogsBloom
	}
	return ""
}

var File_BaseApi_proto protoreflect.FileDescriptor

const file_BaseApi_proto_rawDesc = "" +
	"\n" +
	"\rBaseApi.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xd8\x05\n" +
	"\tBaseBlock\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\tR\n" +
	"parentHash\x12#\n" +
	"\rfee_recipient\x18\x02 \x01(\tR\ffeeRecipient\x12\x1d\n" +
	"\n" +
	"state_root\x18\x03 \x01(\fR\tstateRoot\x12#\n" +
	"\rreceipts_root\x18\x04 \x01(\fR\freceiptsRoot\x12\x1d\n" +
	"\n" +
	"logs_bloom\x18\x05 \x01(\fR\tlogsBloom\x12\x1f\n" +
	"\vprev_randao\x18\x06 \x01(\fR\n" +
	"prevRandao\x12!\n" +
	"\fblock_number\x18\a \x01(\x04R\vblockNumber\x12\x1b\n" +
	"\tgas_limit\x18\b \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\t \x01(\x04R\agasUsed\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"extra_data\x18\v \x01(\fR\textraData\x12'\n" +
	"\x10base_fee_per_gas\x18\f \x03(\x04R\rbaseFeePerGas\x12\x1d\n" +
	"\n" +
	"block_hash\x18\r \x01(\tR\tblockHash\x12\"\n" +
	"\ftransactions\x18\x0e \x03(\fR\ftransactions\x12-\n" +
	"\vwithdrawals\x18\x0f \x03(\v2\v.WithdrawalR\vwithdrawals\x12@\n" +
	"\rblob_gas_used\x18\x10 \x01(\v2\x1c.google.protobuf.UInt64ValueR\vblobGasUsed\x12D\n" +
	"\x0fexcess_blob_gas\x18\x11 \x01(\v2\x1c.google.protobuf.UInt64ValueR\rexcessBlobGas\x12F\n" +
	"\x10withdrawals_root\x18\x12 \x01(\v2\x1b.google.protobuf.BytesValueR\x0fwithdrawalsRoot\"r\n" +
	"\n" +
	"Withdrawal\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x1c\n" +
	"\tvalidator\x18\x02 \x01(\x04R\tvalidator\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\fR\aaddress\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\" \n" +
	"\x1eGetRawFlashBlocksStreamRequest\"\x17\n" +
	"\x15GetBlockStreamRequest\"@\n" +
	"\x16SendTransactionRequest\x12&\n" +
	"\x0erawTransaction\x18\x01 \x01(\tR\x0erawTransaction\"1\n" +
	"\x17SendTransactionResponse\x12\x16\n" +
	"\x06txHash\x18\x01 \x01(\tR\x06txHash\"\x16\n" +
	"\x14FlashBlockStrRequest\"4\n" +
	"\x18RawFlashBlockStrResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\"+\n" +
	")GetNewFlashblockTransactionsStreamRequest\"f\n" +
	"'NewFlashblockTransactionAccessListEntry\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12!\n" +
	"\fstorage_keys\x18\x02 \x03(\tR\vstorageKeys\"\xdd\x02\n" +
	"\x1bNewFlashblockTransactionLog\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\tR\tblockHash\x12!\n" +
	"\fblock_number\x18\x05 \x01(\tR\vblockNumber\x12'\n" +
	"\x0fblock_timestamp\x18\x06 \x01(\tR\x0eblockTimestamp\x12)\n" +
	"\x10transaction_hash\x18\a \x01(\tR\x0ftransactionHash\x12+\n" +
	"\x11transaction_index\x18\b \x01(\tR\x10transactionIndex\x12\x1b\n" +
	"\tlog_index\x18\t \x01(\tR\blogIndex\x12\x18\n" +
	"\aremoved\x18\n" +
	" \x01(\bR\aremoved\"\xb2\a\n" +
	"\x18NewFlashblockTransaction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12\x10\n" +
	"\x03gas\x18\x04 \x01(\tR\x03gas\x12%\n" +
	"\x0fmax_fee_per_gas\x18\x05 \x01(\tR\fmaxFeePerGas\x126\n" +
	"\x18max_priority_fee_per_gas\x18\x06 \x01(\tR\x14maxPriorityFeePerGas\x12,\n" +
	"\x02to\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x02to\x12\x14\n" +
	"\x05value\x18\b \x01(\tR\x05value\x12I\n" +
	"\vaccess_list\x18\t \x03(\v2(.NewFlashblockTransactionAccessListEntryR\n" +
	"accessList\x12\x14\n" +
	"\x05input\x18\n" +
	" \x01(\tR\x05input\x12\f\n" +
	"\x01r\x18\v \x01(\tR\x01r\x12\f\n" +
	"\x01s\x18\f \x01(\tR\x01s\x12\x19\n" +
	"\by_parity\x18\r \x01(\tR\ayParity\x12\f\n" +
	"\x01v\x18\x0e \x01(\tR\x01v\x12\x12\n" +
	"\x04hash\x18\x0f \x01(\tR\x04hash\x12;\n" +
	"\n" +
	"block_hash\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueR\tblockHash\x12!\n" +
	"\fblock_number\x18\x11 \x01(\tR\vblockNumber\x12+\n" +
	"\x11transaction_index\x18\x12 \x01(\tR\x10transactionIndex\x12'\n" +
	"\x0fblock_timestamp\x18\x13 \x01(\tR\x0eblockTimestamp\x12\x12\n" +
	"\x04from\x18\x14 \x01(\tR\x04from\x12\x1b\n" +
	"\tgas_price\x18\x15 \x01(\tR\bgasPrice\x120\n" +
	"\x04logs\x18\x16 \x03(\v2\x1c.NewFlashblockTransactionLogR\x04logs\x12\x19\n" +
	"\bgas_used\x18\x17 \x01(\tR\agasUsed\x12\x16\n" +
	"\x06status\x18\x18 \x01(\tR\x06status\x12.\n" +
	"\x13cumulative_gas_used\x18\x19 \x01(\tR\x11cumulativeGasUsed\x12G\n" +
	"\x10contract_address\x18\x1a \x01(\v2\x1c.google.protobuf.StringValueR\x0fcontractAddress\x12\x1d\n" +
	"\n" +
	"logs_bloom\x18\x1b \x01(\tR\tlogsBloom2\xce\x02\n" +
	"\aBaseApi\x12D\n" +
	"\x0fSendTransaction\x12\x17.SendTransactionRequest\x1a\x18.SendTransactionResponse\x126\n" +
	"\x0eGetBlockStream\x12\x16.GetBlockStreamRequest\x1a\n" +
	".BaseBlock0\x01\x12V\n" +
	"\x16GetRawFlashBlockStream\x12\x1f.GetRawFlashBlocksStreamRequest\x1a\x19.RawFlashBlockStrResponse0\x01\x12m\n" +
	"\"GetNewFlashblockTransactionsStream\x12*.GetNewFlashblockTransactionsStreamRequest\x1a\x19.NewFlashblockTransaction0\x01B\n" +
	"Z\b./basepbb\x06proto3"

var (
	file_BaseApi_proto_rawDescOnce sync.Once
	file_BaseApi_proto_rawDescData []byte
)

func file_BaseApi_proto_rawDescGZIP() []byte {
	file_BaseApi_proto_rawDescOnce.Do(func() {
		file_BaseApi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_BaseApi_proto_rawDesc), len(file_BaseApi_proto_rawDesc)))
	})
	return file_BaseApi_proto_rawDescData
}

var file_BaseApi_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_BaseApi_proto_goTypes = []any{
	(*BaseBlock)(nil),                                 // 0: BaseBlock
	(*Withdrawal)(nil),                                // 1: Withdrawal
	(*GetRawFlashBlocksStreamRequest)(nil),            // 2: GetRawFlashBlocksStreamRequest
	(*GetBlockStreamRequest)(nil),                     // 3: GetBlockStreamRequest
	(*SendTransactionRequest)(nil),                    // 4: SendTransactionRequest
	(*SendTransactionResponse)(nil),                   // 5: SendTransactionResponse
	(*FlashBlockStrRequest)(nil),                      // 6: FlashBlockStrRequest
	(*RawFlashBlockStrResponse)(nil),                  // 7: RawFlashBlockStrResponse
	(*GetNewFlashblockTransactionsStreamRequest)(nil), // 8: GetNewFlashblockTransactionsStreamRequest
	(*NewFlashblockTransactionAccessListEntry)(nil),   // 9: NewFlashblockTransactionAccessListEntry
	(*NewFlashblockTransactionLog)(nil),               // 10: NewFlashblockTransactionLog
	(*NewFlashblockTransaction)(nil),                  // 11: NewFlashblockTransaction
	(*wrapperspb.UInt64Value)(nil),                    // 12: google.protobuf.UInt64Value
	(*wrapperspb.BytesValue)(nil),                     // 13: google.protobuf.BytesValue
	(*wrapperspb.StringValue)(nil),                    // 14: google.protobuf.StringValue
}
var file_BaseApi_proto_depIdxs = []int32{
	1,  // 0: BaseBlock.withdrawals:type_name -> Withdrawal
	12, // 1: BaseBlock.blob_gas_used:type_name -> google.protobuf.UInt64Value
	12, // 2: BaseBlock.excess_blob_gas:type_name -> google.protobuf.UInt64Value
	13, // 3: BaseBlock.withdrawals_root:type_name -> google.protobuf.BytesValue
	14, // 4: NewFlashblockTransaction.to:type_name -> google.protobuf.StringValue
	9,  // 5: NewFlashblockTransaction.access_list:type_name -> NewFlashblockTransactionAccessListEntry
	14, // 6: NewFlashblockTransaction.block_hash:type_name -> google.protobuf.StringValue
	10, // 7: NewFlashblockTransaction.logs:type_name -> NewFlashblockTransactionLog
	14, // 8: NewFlashblockTransaction.contract_address:type_name -> google.protobuf.StringValue
	4,  // 9: BaseApi.SendTransaction:input_type -> SendTransactionRequest
	3,  // 10: BaseApi.GetBlockStream:input_type -> GetBlockStreamRequest
	2,  // 11: BaseApi.GetRawFlashBlockStream:input_type -> GetRawFlashBlocksStreamRequest
	8,  // 12: BaseApi.GetNewFlashblockTransactionsStream:input_type -> GetNewFlashblockTransactionsStreamRequest
	5,  // 13: BaseApi.SendTransaction:output_type -> SendTransactionResponse
	0,  // 14: BaseApi.GetBlockStream:output_type -> BaseBlock
	7,  // 15: BaseApi.GetRawFlashBlockStream:output_type -> RawFlashBlockStrResponse
	11, // 16: BaseApi.GetNewFlashblockTransactionsStream:output_type -> NewFlashblockTransaction
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_BaseApi_proto_init() }
func file_BaseApi_proto_init() {
	if File_BaseApi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_BaseApi_proto_rawDesc), len(file_BaseApi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_BaseApi_proto_goTypes,
		DependencyIndexes: file_BaseApi_proto_depIdxs,
		MessageInfos:      file_BaseApi_proto_msgTypes,
	}.Build()
	File_BaseApi_proto = out.File
	file_BaseApi_proto_goTypes = nil
	file_BaseApi_proto_depIdxs = nil
}
